version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-demo-woensdag"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ghvaajc0i25f"
s3_prefix = "sam-demo-woensdag"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
